// @see https://docs.fivem.net/docs/game-references/blips/
// TODO Add blips when you need it
export const enum BlipIcons {
	radar_cable_car = 36,
	radar_police_station = 60,
	radar_hospital = 61,
	radar_clothes_store = 73,
	radar_tattoo = 75,
	radar_bar = 93,
	radar_car_wash = 100,
	radar_off_road_racing = 127,
	radar_cinema = 135,
	radar_hunting = 141,
	radar_mp_noise = 161,
	radar_gang_vehicle = 225,
	radar_horde = 305,
	radar_jerry_can = 361,
	radar_mask = 362,
	radar_player_heli = 422,
	radar_temp_3 = 431,
	radar_bennys = 446,
	radar_truck = 477,
	radar_package = 501,
	radar_drugs_package = 514
}

export const enum BlipColor {
	WHITE,
	RED,
	GREEN, // Red ennemy and blue friendly
	BLUE = 3, // Red ennemy,
	YELLOW = 5,
	VIOLET,
	PINK,
	LIGHT_ORANGE,
	LIGHT_GREEN = 11,
	LIGHT_PURPLE = 13,
	DARK_PURPLE,
	CYAN,
	ORANGE = 17,
	LIGHT_BLUE_2,
	DARK_PINK,
	DARK_ORANGE = 21,
	LIGHT_GRAY,
	LIGHT_PINK,
	LEMON_GREEN,
	FOREST_GREEN,
	ELECTRIC_BLUE,
	BRIGHT_PURPLE,
	DARK_YELLOW,
	DARK_BLUE,
	DARK_CYAN,
	LIGHT_BROWN,
	LIGHT_BLUE,
	LIGHT_YELLOW,
	BEIGE = 36,
	DARK_GRAY = 40,
	PINK_RED,
	GOLD = 46,
	BRILLIANT_ROSE = 48,
	MEDIUM_PURPLE = 50,
	SALMON,
	DARK_GREEN,
	BLIZZARD_BLUE,
	ORACLE_BLUE,
	SILVER,
	BROWN,
	EAST_BAY = 58,
	MULBERRY_PINK = 61,
	ALTO_GRAY,
	JELLY_BEAN_BLUE,
	MAMBA = 65,
	TRANSPARENT_BLACK = 72,
	DEEP_RED = 76,
	TRANSPARENT_RED = 79,
	TRANSPARENT_BLUE,
	PURPLE = 83
}
